### ISSUE TITLE
How could I change the sys/bus/dsa/device/dsa0/pasid_enable to 1?

### ISSUE THREAD

**Issue by chen982** [intel/idxd-config#5]
I have the config_pci_pasid = y, but it doesn't works

**Comment by davejiang** [comment]
Hi Tianchen, you need to turn VTd on in your BIOS and then pass in intel_iommu=on,sm_on for kernel boot parameter.

**Comment by chen982** [comment]
It works, thank you very much

**Comment by davejiang** [comment]
Issue resolved.

**Comment by davejiang** [comment]
Well, unless your qemu and your kernel supports vIOMMU with scalable mode support then you won't get pasid on the guest. I don't think those support are upstream yet.

**Comment by chen982** [comment]
So how can I use the DSA device in the QEMU? Is there another way to use it? Now I use it in host only with the help of accel_config , and pass dsa0 using vfio to QEMU, and want to use it with the accel_config，but this occurs

**Comment by davejiang** [comment]
You can only use it without vIOMMU support on guest right now. There's significant rework upstream on vIOMMU (/dev/iommu) right now and that support is pending the fallout of that. So I don't think you'll get that support any time soon.

**Comment by chen982** [comment]
use it without vIOMMU support ? Is there some examples or codes to use the DSA in that way ? In the spec doc it seems to abstract ,so I use the dsa with the help of accel_config

**Comment by davejiang** [comment]
It's no different than using DSA with intel_iommu=off or intel_iommu=on on the host. It essentially makes you run legacy mode. Which also means your user memory must be pinned (since you don't have SVM support) and the descriptors must be programmed with PA or IOVA. 

I'm not sure what you mean by with the help of accel-config. accel-config gives you a front end to configure the device. It has nothing to do with the operation of the device.

**Comment by chen982** [comment]
Thanks very much for you reply, I get it and will have a try
